---
# tasks file for roles/apache_install
- name: httpd package is present
  #dnf:
  #  name: httpd
  #  state: latest
  shell: /usr/bin/dnf install -y httpd

- name: latest index.html file is present
  template:
    src: files/index.html
    dest: /var/www/html/

- name: httpd is started
  service:
    name: httpd
    state: started